branch-defaults:
  default:
    environment: Test-app-env
environment-defaults:
  Test-app-env:
    branch: null
    repository: null
global:
  application_name: test-app
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
